// <auto-generated />
using System;
using ApiVault.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ApiVault.Infrastructure.Persistence.OracleMigrations
{
    [DbContext(typeof(ApiVaultDbContext))]
    partial class ApiVaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiVault.Domain.Entities.ApiAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("BusinessAreaId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("CreatorEmail")
                        .HasMaxLength(320)
                        .HasColumnType("NVARCHAR2(320)");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<Guid>("DevelopmentTeamId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ExternalReferenceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<Guid>("PublishingApplicationId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("VendorName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessAreaId");

                    b.HasIndex("DevelopmentTeamId");

                    b.HasIndex("PublishingApplicationId");

                    b.HasIndex("Name", "PublishingApplicationId")
                        .IsUnique();

                    b.ToTable("API_ASSET", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.ApiEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("ApiVersionId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("PathParametersJson")
                        .HasColumnType("NCLOB");

                    b.Property<string>("QueryParametersJson")
                        .HasColumnType("NCLOB");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("RequestHeadersJson")
                        .HasColumnType("NCLOB");

                    b.Property<string>("RequestPayloadSample")
                        .HasColumnType("NCLOB");

                    b.Property<string>("ResponseBodySample")
                        .HasColumnType("NCLOB");

                    b.Property<string>("ResponseHeadersSampleJson")
                        .HasColumnType("NCLOB");

                    b.Property<string>("SoapAction")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("SuccessStatusCodesJson")
                        .HasColumnType("NCLOB");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApiVersionId", "RelativePath", "HttpMethod")
                        .IsUnique();

                    b.ToTable("API_ENDPOINT", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.ApiEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("ApiVersionId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("EnvironmentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApiVersionId", "EnvironmentType")
                        .IsUnique();

                    b.ToTable("API_ENVIRONMENT", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.ApiVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("ApiAssetId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("AuthenticationConfigJson")
                        .HasColumnType("NCLOB");

                    b.Property<string>("AuthenticationInstructions")
                        .HasColumnType("NCLOB");

                    b.Property<string>("AuthenticationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("ChangeLog")
                        .HasColumnType("NCLOB");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime?>("DeprecatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<int>("MaxRequestBytes")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("MaxResponseBytes")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("ReleaseDateUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("ReleaseName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime?>("RetiredAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApiAssetId", "Version")
                        .IsUnique();

                    b.ToTable("API_VERSION", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("NVARCHAR2(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("APP_USER", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("APP_USER_ROLE", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("NCLOB");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.BusinessArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BUSINESS_AREA", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.DevelopmentTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("NVARCHAR2(320)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DEV_TEAM", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.EnvironmentSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("ApiEnvironmentId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("NCLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApiEnvironmentId", "Name")
                        .IsUnique();

                    b.ToTable("ENV_SECRET", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("BusinessAreaId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<Guid?>("OwnerTeamId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessAreaId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("OwnerTeamId");

                    b.HasIndex("VendorId");

                    b.ToTable("PROJECT_REGISTRY", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.ProjectApiVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("ApiVersionId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("NUMBER(1)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Purpose")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApiVersionId");

                    b.HasIndex("ProjectId", "ApiVersionId")
                        .IsUnique();

                    b.ToTable("PROJECT_API_VER", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("ScreenId");

                    b.HasIndex("RoleId", "ScreenId", "PermissionId")
                        .IsUnique();

                    b.ToTable("ROLE_PERMISSION", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.SecurityPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SEC_PERMISSION", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.SecurityRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SEC_ROLE", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.SecurityScreen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.HasIndex("Route")
                        .IsUnique();

                    b.ToTable("SEC_SCREEN", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.TestExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("ApiEndpointId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("ApiEnvironmentId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("NCLOB");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("NCLOB");

                    b.Property<string>("RequestHeadersJson")
                        .HasColumnType("NCLOB");

                    b.Property<long>("RequestSizeBytes")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("NCLOB");

                    b.Property<string>("ResponseHeadersJson")
                        .HasColumnType("NCLOB");

                    b.Property<long>("ResponseSizeBytes")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApiEndpointId");

                    b.HasIndex("ApiEnvironmentId");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("TEST_EXECUTION", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("SupportEmail")
                        .HasMaxLength(320)
                        .HasColumnType("NVARCHAR2(320)");

                    b.Property<string>("SupportPhone")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TIMESTAMP(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VENDOR", (string)null);
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.ApiAsset", b =>
                {
                    b.HasOne("ApiVault.Domain.Entities.BusinessArea", "BusinessArea")
                        .WithMany("Apis")
                        .HasForeignKey("BusinessAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiVault.Domain.Entities.DevelopmentTeam", "DevelopmentTeam")
                        .WithMany("Apis")
                        .HasForeignKey("DevelopmentTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiVault.Domain.Entities.Project", "PublishingApplication")
                        .WithMany("PublishedApis")
                        .HasForeignKey("PublishingApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessArea");

                    b.Navigation("DevelopmentTeam");

                    b.Navigation("PublishingApplication");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.ApiEndpoint", b =>
                {
                    b.HasOne("ApiVault.Domain.Entities.ApiVersion", "ApiVersion")
                        .WithMany("Endpoints")
                        .HasForeignKey("ApiVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApiVersion");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.ApiEnvironment", b =>
                {
                    b.HasOne("ApiVault.Domain.Entities.ApiVersion", "ApiVersion")
                        .WithMany("Environments")
                        .HasForeignKey("ApiVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApiVersion");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.ApiVersion", b =>
                {
                    b.HasOne("ApiVault.Domain.Entities.ApiAsset", "ApiAsset")
                        .WithMany("Versions")
                        .HasForeignKey("ApiAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApiAsset");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.AppUserRole", b =>
                {
                    b.HasOne("ApiVault.Domain.Entities.SecurityRole", "Role")
                        .WithMany("UserAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiVault.Domain.Entities.AppUser", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.EnvironmentSecret", b =>
                {
                    b.HasOne("ApiVault.Domain.Entities.ApiEnvironment", "ApiEnvironment")
                        .WithMany("Secrets")
                        .HasForeignKey("ApiEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApiEnvironment");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.Project", b =>
                {
                    b.HasOne("ApiVault.Domain.Entities.BusinessArea", "BusinessArea")
                        .WithMany("Projects")
                        .HasForeignKey("BusinessAreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApiVault.Domain.Entities.DevelopmentTeam", "OwnerTeam")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApiVault.Domain.Entities.Vendor", "Vendor")
                        .WithMany("Systems")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BusinessArea");

                    b.Navigation("OwnerTeam");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.ProjectApiVersion", b =>
                {
                    b.HasOne("ApiVault.Domain.Entities.ApiVersion", "ApiVersion")
                        .WithMany("ProjectLinks")
                        .HasForeignKey("ApiVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiVault.Domain.Entities.Project", "Project")
                        .WithMany("ApiLinks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApiVersion");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("ApiVault.Domain.Entities.SecurityPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiVault.Domain.Entities.SecurityRole", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiVault.Domain.Entities.SecurityScreen", "Screen")
                        .WithMany("RolePermissions")
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.SecurityScreen", b =>
                {
                    b.HasOne("ApiVault.Domain.Entities.SecurityScreen", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.TestExecution", b =>
                {
                    b.HasOne("ApiVault.Domain.Entities.ApiEndpoint", "ApiEndpoint")
                        .WithMany("TestExecutions")
                        .HasForeignKey("ApiEndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiVault.Domain.Entities.ApiEnvironment", "ApiEnvironment")
                        .WithMany("TestExecutions")
                        .HasForeignKey("ApiEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApiEndpoint");

                    b.Navigation("ApiEnvironment");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.ApiAsset", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.ApiEndpoint", b =>
                {
                    b.Navigation("TestExecutions");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.ApiEnvironment", b =>
                {
                    b.Navigation("Secrets");

                    b.Navigation("TestExecutions");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.ApiVersion", b =>
                {
                    b.Navigation("Endpoints");

                    b.Navigation("Environments");

                    b.Navigation("ProjectLinks");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.BusinessArea", b =>
                {
                    b.Navigation("Apis");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.DevelopmentTeam", b =>
                {
                    b.Navigation("Apis");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.Project", b =>
                {
                    b.Navigation("ApiLinks");

                    b.Navigation("PublishedApis");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.SecurityPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.SecurityRole", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.SecurityScreen", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ApiVault.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("Systems");
                });
#pragma warning restore 612, 618
        }
    }
}
